### ISSUE TITLE
Update flag events not notifying through webhooks

### ISSUE THREAD

**Issue by vinodhreddygs** [andris9/imapapi#18] opened 2020-05-26 11:23 UTC
Hi @andris9 ,

Whenever new emails comes to the register email account with IMAP will notify to my application through webhooks. But whenever I unread an email, those update flags notifications not triggering by the webhooks(But update flags notifications will get when I run the code local but not on the server).

Thanks.

**Comment by andris9** [comment] 2020-05-26 11:26
If you mark messages as seen/unseen using IMAP API then you do not get a webhook for it as you already know about this change. IMAP API notifies only about unknown changes in the system.

**Comment by vinodhreddygs** [comment] 2020-05-26 11:30
@andris9 Iam not marking seen/unseen using IMAP API. Iam marking unseen manually in the INBOX of register email account with IMAP.

**Comment by andris9** [comment] 2020-05-26 11:32
If you do not get expected notifications, then you should enable logging for this account, mark messages as read/unread in your email client to trigger changes and then download recorded logs for this account to see what is going on and why IMAP API is not able to pick up the changes.

**Comment by vinodhreddygs** [comment] 2020-05-26 11:43
@andris9 When I unread an email the below logs were logged in the Redis but I didn't get any webhooks for this update. Please let me know if you find any issues in the below logs:
```
{"level":"trace","t":1590493176199,"cid":"gbohoz2semlgf7l4gufy","lo":13,"src":"s","msg":"* 15 FETCH (UID 19 MODSEQ (5447) FLAGS ())"}
{"level":"trace","t":1590493177215,"lo":14,"msg":"Requesting lock","path":"[Gmail]/All Mail","lockId":7}
{"level":"trace","t":1590493177215,"lo":15,"msg":"Mailbox lock acquired","path":"[Gmail]/All Mail","lockId":7}
{"level":"trace","t":1590493177215,"lo":16,"msg":"Mailbox lock released","lockId":7}
```

**Comment by vinodhreddygs** [comment] 2020-05-26 11:48
When I marked seen/unseen for multiple times below logs are logged but didn't get any notification for any those changes:
`{"level":"trace","t":1590493176199,"cid":"gbohoz2semlgf7l4gufy","lo":13,"src":"s","msg":"* 15 FETCH (UID 19 MODSEQ (5447) FLAGS ())"}
{"level":"trace","t":1590493177215,"lo":14,"msg":"Requesting lock","path":"[Gmail]/All Mail","lockId":7}
{"level":"trace","t":1590493177215,"lo":15,"msg":"Mailbox lock acquired","path":"[Gmail]/All Mail","lockId":7}
{"level":"trace","t":1590493177215,"lo":16,"msg":"Mailbox lock released","lockId":7}
{"level":"debug","t":1590493476200,"lo":17,"src":"c","msg":"breaking IDLE"}
{"level":"debug","t":1590493476359,"cid":"gbohoz2semlgf7l4gufy","lo":18,"src":"s","msg":"15 OK IDLE terminated (Success)"}
{"level":"debug","t":1590493476359,"cid":"gbohoz2semlgf7l4gufy","lo":19,"src":"s","msg":"16 NOOP"}
{"level":"debug","t":1590493476514,"cid":"gbohoz2semlgf7l4gufy","lo":20,"src":"s","msg":"16 OK Success"}
{"level":"debug","t":1590493476515,"cid":"gbohoz2semlgf7l4gufy","lo":21,"src":"s","msg":"17 IDLE"}
{"level":"debug","t":1590493476675,"cid":"gbohoz2semlgf7l4gufy","lo":22,"src":"s","msg":"+ idling"}
{"level":"debug","t":1590493476675,"lo":23,"src":"c","msg":"initiated IDLE"}
{"level":"debug","t":1590493479094,"lo":24,"src":"c","msg":"breaking IDLE"}
{"level":"debug","t":1590493479255,"cid":"gbohoz2semlgf7l4gufy","lo":25,"src":"s","msg":"17 OK IDLE terminated (Success)"}
{"level":"debug","t":1590493479255,"cid":"gbohoz2semlgf7l4gufy","lo":26,"src":"s","msg":"18 STATUS INBOX (UIDNEXT MESSAGES HIGHESTMODSEQ UIDVALIDITY)"}
{"level":"debug","t":1590493479437,"cid":"gbohoz2semlgf7l4gufy","lo":27,"src":"s","msg":"* STATUS \"INBOX\" (HIGHESTMODSEQ 5472 MESSAGES 14 UIDNEXT 15 UIDVALIDITY 1)"}
{"level":"debug","t":1590493479438,"cid":"gbohoz2semlgf7l4gufy","lo":28,"src":"s","msg":"18 OK Success"}
{"level":"debug","t":1590493479439,"cid":"gbohoz2semlgf7l4gufy","lo":29,"src":"s","msg":"19 STATUS \"[Gmail]/Drafts\" (UIDNEXT MESSAGES HIGHESTMODSEQ UIDVALIDITY)"}
{"level":"debug","t":1590493479599,"cid":"gbohoz2semlgf7l4gufy","lo":30,"src":"s","msg":"* STATUS \"[Gmail]/Drafts\" (HIGHESTMODSEQ 5472 MESSAGES 0 UIDNEXT 5 UIDVALIDITY 6)"}
{"level":"debug","t":1590493479599,"cid":"gbohoz2semlgf7l4gufy","lo":31,"src":"s","msg":"19 OK Success"}
{"level":"debug","t":1590493479612,"cid":"gbohoz2semlgf7l4gufy","lo":32,"src":"s","msg":"1A STATUS \"[Gmail]/Important\" (UIDNEXT MESSAGES HIGHESTMODSEQ UIDVALIDITY)"}
{"level":"debug","t":1590493479766,"cid":"gbohoz2semlgf7l4gufy","lo":33,"src":"s","msg":"* STATUS \"[Gmail]/Important\" (HIGHESTMODSEQ 5472 MESSAGES 12 UIDNEXT 13 UIDVALIDITY 9)"}
{"level":"debug","t":1590493479766,"cid":"gbohoz2semlgf7l4gufy","lo":34,"src":"s","msg":"1A OK Success"}
{"level":"debug","t":1590493479771,"cid":"gbohoz2semlgf7l4gufy","lo":35,"src":"s","msg":"1B STATUS \"[Gmail]/Sent Mail\" (UIDNEXT MESSAGES HIGHESTMODSEQ UIDVALIDITY)"}
{"level":"debug","t":1590493479927,"cid":"gbohoz2semlgf7l4gufy","lo":36,"src":"s","msg":"* STATUS \"[Gmail]/Sent Mail\" (HIGHESTMODSEQ 5472 MESSAGES 1 UIDNEXT 2 UIDVALIDITY 5)"}
{"level":"debug","t":1590493479927,"cid":"gbohoz2semlgf7l4gufy","lo":37,"src":"s","msg":"1B OK Success"}
{"level":"debug","t":1590493479931,"cid":"gbohoz2semlgf7l4gufy","lo":38,"src":"s","msg":"1C STATUS \"[Gmail]/Spam\" (UIDNEXT MESSAGES HIGHESTMODSEQ UIDVALIDITY)"}
{"level":"debug","t":1590493480085,"cid":"gbohoz2semlgf7l4gufy","lo":39,"src":"s","msg":"* STATUS \"[Gmail]/Spam\" (HIGHESTMODSEQ 5472 MESSAGES 0 UIDNEXT 1 UIDVALIDITY 3)"}
{"level":"debug","t":1590493480085,"cid":"gbohoz2semlgf7l4gufy","lo":40,"src":"s","msg":"1C OK Success"}
{"level":"debug","t":1590493480091,"cid":"gbohoz2semlgf7l4gufy","lo":41,"src":"s","msg":"1D STATUS \"[Gmail]/Starred\" (UIDNEXT MESSAGES HIGHESTMODSEQ UIDVALIDITY)"}
{"level":"debug","t":1590493480251,"cid":"gbohoz2semlgf7l4gufy","lo":42,"src":"s","msg":"* STATUS \"[Gmail]/Starred\" (HIGHESTMODSEQ 5472 MESSAGES 0 UIDNEXT 1 UIDVALIDITY 4)"}
{"level":"debug","t":1590493480251,"cid":"gbohoz2semlgf7l4gufy","lo":43,"src":"s","msg":"1D OK Success"}
{"level":"debug","t":1590493480263,"cid":"gbohoz2semlgf7l4gufy","lo":44,"src":"s","msg":"1E STATUS \"[Gmail]/Trash\" (UIDNEXT MESSAGES HIGHESTMODSEQ UIDVALIDITY)"}
{"level":"debug","t":1590493480419,"cid":"gbohoz2semlgf7l4gufy","lo":45,"src":"s","msg":"* STATUS \"[Gmail]/Trash\" (HIGHESTMODSEQ 5472 MESSAGES 0 UIDNEXT 1 UIDVALIDITY 2)"}
{"level":"debug","t":1590493480420,"cid":"gbohoz2semlgf7l4gufy","lo":46,"src":"s","msg":"1E OK Success"}
{"level":"trace","t":1590493480431,"lo":47,"msg":"Requesting lock","path":"[Gmail]/All Mail","lockId":8}
{"level":"trace","t":1590493480431,"lo":48,"msg":"Mailbox lock acquired","path":"[Gmail]/All Mail","lockId":8}
{"level":"trace","t":1590493480431,"lo":49,"msg":"Mailbox lock released","lockId":8}
{"level":"debug","t":1590493480432,"cid":"gbohoz2semlgf7l4gufy","lo":50,"src":"s","msg":"1F IDLE"}
{"level":"debug","t":1590493480592,"cid":"gbohoz2semlgf7l4gufy","lo":51,"src":"s","msg":"+ idling"}
{"level":"debug","t":1590493480592,"lo":52,"src":"c","msg":"initiated IDLE"}
{"level":"trace","t":1590493500613,"cid":"gbohoz2semlgf7l4gufy","lo":53,"src":"s","msg":"* 15 FETCH (UID 19 MODSEQ (5475) FLAGS (\\Seen))"}
{"level":"trace","t":1590493501622,"lo":54,"msg":"Requesting lock","path":"[Gmail]/All Mail","lockId":9}
{"level":"trace","t":1590493501623,"lo":55,"msg":"Mailbox lock acquired","path":"[Gmail]/All Mail","lockId":9}
{"level":"trace","t":1590493501623,"lo":56,"msg":"Mailbox lock released","lockId":9}
`

**Comment by andris9** [comment] 2020-05-26 12:24
Are you running the latest version of IMAP API?

**Comment by vinodhreddygs** [comment] 2020-05-26 12:52
@andris9 I just gone through your documentation and I'am using the APIs which you are provided in Swagger API docs that's it. From where I can check the version of IMAP API ?

**Comment by andris9** [comment] 2020-05-26 13:00
Check `package.json` file, there should be a line like this: `"version": "1.2.18",`

**Comment by vinodhreddygs** [comment] 2020-05-27 06:35
> version": "1.2.18

@andris9 I have not installed any IMAP Packages to check the version. I have connected IMAP by running the command that you have given in this documentation. i.e. `$ npx imapapi --dbs.redis="redis://127.0.0.1:6379"`
From there I can see the version at the bottom of the page i.e. `"version": "1.2.18"`. Please refer the below screenshot for the reference:
![image](https://user-images.githubusercontent.com/37541181/82985813-55f20000-a012-11ea-99ed-dbcef5b9d708.png)

**Comment by andris9** [comment] 2020-05-27 06:58
This seems like the latest version. Would it be possible to get full session logs? 
1. Enable logging
2. Restart IMAP API so all connections would be re-initialized
3. Try to get a situation where IMAP API does not emit notifications for unseen/seen changes
4. Download logs and send these to andris.reinman@gmail.com so I would be able to analyze

**Comment by vinodhreddygs** [comment] 2020-05-27 09:06
> 4\. andris.reinman@gmail.com

@andris9 I sent you an email with logs. Please look into it.

**Comment by andris9** [comment] 2020-05-28 15:13
I checked the logs, unfortunately these were partial so I was not able to trace potential issues with state changes. I'm unable to reproduce this situation myself as well, so I have no idea what could cause it for you.

I'll keep this ticket open, maybe someone else has the same issue in the future and is able to debug the exact reason for it themselves.

**Comment by 712163** [comment] 2020-12-16 02:43
webhook not work on win10

**Comment by andris9** [comment] 2020-12-21 12:27
Closing as there has been no additional info.

**Closed by andris9** 2020-12-21 12:27 UTC
