### ISSUE TITLE
OFFICE365 - textType plain/html not work

### ISSUE THREAD

**Issue by wciurzynski** [andris9/imapapi#55] opened 2021-01-25 16:06 UTC
Version 1.4.6

Retrieves message text - this endoint returns content of mail. If I specified textType to plain or html, I get empty string. But if I pass * as textType I get html in field 'plain'.

After adding more logs I found error - file /lib/connection.js in function getText(textId, options) in line 767.
If I pass textType as "html" a variable "result" should have field "html" but has only "plain" and vice versa.

**Comment by andris9** [comment] 2021-01-28 09:11
Could you provide IMAP logs for that transaction?

**Comment by ricus-zero2one** [comment] 2021-02-17 06:14
Hi @andris9 

I seem to be experiencing the same for outlook accounts. It looks like if there is only an html body, it gets sent back in the plain key, see below example of one of these emails:

![image](https://user-images.githubusercontent.com/17425015/108163549-e835b900-70f7-11eb-9b92-a9677aec92b9.png)

It has the encoded size for html, it just looks like the key that is getting used is wrong?

If I take a look at the same mailbox, but an email that contains both html and plain text, it looks as follows:

![image](https://user-images.githubusercontent.com/17425015/108163675-14513a00-70f8-11eb-966d-8102abed6d71.png)

**Comment by andris9** [comment] 2021-02-17 07:12
@ricus-zero2one can you provide IMAP logs? The message structure is derived from the output of BODYSTRUCTURE.

**Comment by ricus-zero2one** [comment] 2021-02-17 08:14
@andris9 are you referring to the logs functionality provided by imap-api?

**Comment by andris9** [comment] 2021-02-17 08:26
Yes. Or copy and paste the logs from console. Both include all IMAP commands sent and received.

**Comment by ricus-zero2one** [comment] 2021-02-17 08:41
Hi again @andris9 

Okay so I logged into outlook.com, sent an email, and waited a little while but the webhook wasn't coming through, so I requested a reconnect which got the message (I've noticed I don't get the imap event for the outlook account instantly, takes minutes sometimes, reconnect normally gets it dues to just querying the mails I think)

I've attached the log export, look for what happened after the last reconnect request, but it's probably this part:

```{"level":"trace","t":1613550773109,"cid":"12j1v2675908y6kqlu5g","lo":185,"src":"s","msg":"* 92 FETCH (UID 312 FLAGS (\\Seen))"}
{"level":"debug","t":1613550773111,"cid":"12j1v2675908y6kqlu5g","lo":186,"src":"s","msg":"13 OK FETCH completed."}
{"level":"debug","t":1613550773113,"cid":"12j1v2675908y6kqlu5g","lo":187,"src":"s","msg":"14 UID FETCH 312 (UID FLAGS BODYSTRUCTURE ENVELOPE INTERNALDATE RFC822.SIZE)"}
{"level":"trace","t":1613550773300,"cid":"12j1v2675908y6kqlu5g","lo":188,"src":"s","msg":"* 92 FETCH (UID 312 FLAGS (\\Seen) BODYSTRUCTURE (\"text\" \"html\" (\"charset\" \"iso-8859-1\") NIL NIL \"quoted-printable\" 460 13 NIL NIL \"en-US\" NIL) ENVELOPE (\"Wed, 17 Feb 2021 08:30:20 +0000\" \"body check 1030\" ((\"zero2onedigital021@outlook.com\" NIL \"zero2onedigital021\" \"outlook.com\")) NIL NIL ((\"Ricus Swanepoel\" NIL \"ricus\" \"zero2one.co.za\")) NIL NIL NIL \"<AM5PR0701MB27716485CD566BA854A2F51DC1869@AM5PR0701MB2771.eurprd07.prod.outlook.com>\") INTERNALDATE \"17-Feb-2021 10:30:21 +0200\" RFC822.SIZE 41882)"}
```

The `body check 1030` is the test email in question. 


[logs-574f44c4-f233-4f10-8129-54ce7c080837 (11).log](https://github.com/andris9/imapapi/files/5994360/logs-574f44c4-f233-4f10-8129-54ce7c080837.11.log)

**Comment by andris9** [comment] 2021-02-17 11:47
@ricus-zero2one  Thanks for the logs. Could you also provide the EML formatted message file (eg. the source of the email), so I could upload it to my own email server for comparisons?

**Comment by ricus-zero2one** [comment] 2021-02-17 12:11
Hi @andris9 

I was able to reproduce with this raw message

[dump.txt](https://github.com/andris9/imapapi/files/5995516/dump.txt)

I changed the To but that shouldn't make a difference

**Comment by andris9** [comment] 2021-02-17 12:59
Thank you. I can verify that there seems to be a bug. On the following screenshot right image is from Dovecot and the left one is from O365

<img width="966" alt="Screenshot 2021-02-17 at 14 56 29" src="https://user-images.githubusercontent.com/132242/108207474-7594ff80-7130-11eb-89e5-498e1c57a0f3.png">

**Comment by ricus-zero2one** [comment] 2021-02-17 13:13
Okay great, I'm glad you were able to reproduce it

**Comment by andris9** [comment] 2021-02-17 13:46
Fixed in v1.4.7

**Closed by andris9** 2021-02-17 13:46 UTC

**Comment by ricus-zero2one** [comment] 2021-02-17 13:48
much appreciated @andris9

**Comment by ricus-zero2one** [comment] 2021-02-17 14:05
Hi @andris9 

I'm testing and got the html body for that and subsequent emails now, however I'm seeing a new key `alternative` where it used to be `plain`

![image](https://user-images.githubusercontent.com/17425015/108215164-b1809280-7139-11eb-8335-d53f1e26d648.png)

Has plain been renamed to alternative with this update? before 1.4.7 that key was always plain (matching keys in `encodedSize`)

**Comment by andris9** [comment] 2021-02-17 14:10
It is supposed to be `plain`. I can't seem to replicate this. Can you provide a message with such output?

**Comment by ricus-zero2one** [comment] 2021-02-17 14:25
I can replicate with the below:

[dump2.txt](https://github.com/andris9/imapapi/files/5996288/dump2.txt)

It seems to be for all emails now.

From my side, I use the docker image, I destroyed what I had pulled a new image, and booted that one up. It does indicate 1.4.7 on the dashboard

**Comment by andris9** [comment] 2021-02-17 14:33
Well, it seems that trying to avoid hitting a bug in Outlook IMAP implementation created a bug in IMAP API instead.

**Comment by andris9** [comment] 2021-02-17 14:46
Try using v1.4.8

**Comment by ricus-zero2one** [comment] 2021-02-18 05:24
v1.4.8 seems to have fixed this behaviour, thanks @andris9
