### ISSUE TITLE
Cannot acquire mailbox lock

### ISSUE THREAD

**Issue by cyrilledec** [andris9/imapapi#52] opened 2021-01-12 09:47 UTC
**Describe the bug**
when trying to list messages in a mailbox through imapapi we get a `504 Gateway Time-out`error.
after checking imapapi logs it looks like the API is not able to get a lock on the target mailbox.

**To Reproduce**
it's quite random and not easy to reproduce

**Expected behavior**
be able to get lock on the mailbox

**Screenshots**
This is the latest message in logs (we are expecting `Mailbox lock acquired` after that message) : 
```
imapapi[409381]: {"level":10,"time":1610401217568,"pid":409381,"hostname":"ip-10-0-101-148","tid":4,"component":"imap-client","account":"test","sub":"imap-connection","msg":"Requesting lock","path":"INBOX","lockId":514}
```

**Additional context**
When the problem occured I tried to execute exactly the same request for another account/mailbox and it's working.
So i guess there is an issue getting a lock on this specific account/mailbox (probably lock has not been released properly previously)

To avoid this issue, is there a way to automatically release the lock after a period of time ?

**Comment by andris9** [comment] 2021-01-12 10:29
Normally this happens when you make multiple requests against the same account. Due to IMAP protocol limitations IMAP API  always handles requests serially not in parallel so if an earlier request is not finished then you can't get a lock on any mailbox and have to wait until all other pending requests have been completed - if it takes time then your HTTP requests times out before it can actually run the operation.

If IMAP API takes a lock and never releases it then it's a bug. I would need an IMAP transaction log to see what operations were performed in what order.

**Comment by cyrilledec** [comment] 2021-01-12 10:49
Thanks for your prompt answer.
Is there a way to find which lockID is currently locking a mailbox?
I will investigate more and try to provide more details.

**Comment by cyrilledec** [comment] 2021-01-12 13:50
I've checked more in detail logs and it looks like `lockId:628` has never been released : 
```
Jan 11 14:26:10 ip-10-0-101-148 imapapi[409381]: {"level":10,"time":1610375170262,"pid":409381,"hostname":"ip-10-0-101-148","tid":3,"component":"imap-client","account":"test","cid":"176r9ojuhspg336wxy69","sub":"imap-connection","msg":"Requesting lock","path":"INBOX","lockId":627}
Jan 11 14:26:10 ip-10-0-101-148 imapapi[409381]: {"level":10,"time":1610375170262,"pid":409381,"hostname":"ip-10-0-101-148","tid":3,"component":"imap-client","account":"test","cid":"176r9ojuhspg336wxy69","sub":"imap-connection","msg":"Mailbox lock acquired","path":"INBOX","lockId":627}
Jan 11 14:26:20 ip-10-0-101-148 imapapi[409381]: {"level":10,"time":1610375180777,"pid":409381,"hostname":"ip-10-0-101-148","tid":3,"component":"imap-client","account":"test","cid":"176r9ojuhspg336wxy69","sub":"imap-connection","msg":"Requesting lock","path":"INBOX","lockId":628}
Jan 11 14:26:31 ip-10-0-101-148 imapapi[409381]: {"level":10,"time":1610375191194,"pid":409381,"hostname":"ip-10-0-101-148","tid":3,"component":"imap-client","account":"test","cid":"176r9ojuhspg336wxy69","sub":"imap-connection","msg":"Requesting lock","path":"INBOX","lockId":629}
Jan 11 14:26:39 ip-10-0-101-148 imapapi[409381]: {"level":10,"time":1610375199527,"pid":409381,"hostname":"ip-10-0-101-148","tid":3,"component":"imap-client","account":"test","cid":"176r9ojuhspg336wxy69","sub":"imap-connection","msg":"Requesting lock","path":"INBOX","lockId":630}
Jan 11 14:28:36 ip-10-0-101-148 imapapi[409381]: {"level":10,"time":1610375316170,"pid":409381,"hostname":"ip-10-0-101-148","tid":3,"component":"imap-client","account":"test","cid":"176r9ojuhspg336wxy69","sub":"imap-connection","msg":"Requesting lock","path":"INBOX","lockId":631}
Jan 11 14:28:36 ip-10-0-101-148 imapapi[409381]: {"level":10,"time":1610375316234,"pid":409381,"hostname":"ip-10-0-101-148","tid":3,"component":"imap-client","account":"test","cid":"176r9ojuhspg336wxy69","sub":"imap-connection","msg":"Mailbox lock released","lockId":627}
Jan 11 14:28:36 ip-10-0-101-148 imapapi[409381]: {"level":10,"time":1610375316234,"pid":409381,"hostname":"ip-10-0-101-148","tid":3,"component":"imap-client","account":"test","cid":"176r9ojuhspg336wxy69","sub":"imap-connection","msg":"Mailbox lock acquired","path":"INBOX","lockId":628}
```
@andris9 may I send you the log file by email to help troubleshooting this issue?

**Comment by cyrilledec** [comment] 2021-01-14 09:41
@andris9 I think I understand what is our problem : when we call imapapi and we don't get a lock our app is getting a timeout and the request (on our side failed) but on imapapi side the lock is in the queue.
Then when next lock is picked up there is no request which is sent (because our client app already failed) and this lock is never released.
Is there a way to simply reject a lock request (instead of queuing it) when a lock is already in use ?

**Comment by andris9** [comment] 2021-07-14 10:38
A lot has changed during the last 6 months. I don't know if the issue is still there, I have not been able to re-create it (all locks should be cleared automatically) and no-one else has complained, so closing this issue for now.

**Closed by andris9** 2021-07-14 10:38 UTC
